pipeline{
    agent none
    stages{
        stage('backend'){
            agent{ docker{ image 'node:alpine'}}

            steps{
                sh "node --version"
            }
        }

        stage('frontend'){
            agent{docker{ image 'node:alpine'}}
            steps{
                sh "node --version"
            }
        }

        stage('database'){
            agent{docker{image 'mysql'}}
            steps{
                sh "select * from 1"
            }
        }
    }
}