pipeline{
    agent none
    stages{
        stage('java-backend'){
            agent{ docker{ image 'node:alpine'}}

            steps{
                sh "node --version"
            }
        }

        stage('frontend'){
            agent{docker{ image 'node:alpine'}}
            steps{
                sh "node --version"
            }
        }

        stage('database'){
            agent{docker{image 'mysql'}}
            steps{
                sh "echo mysql installed"
            }
        }
    }
}