pipeline{
    agent{
        docker{
            image "node:slim"
            args "-p 3003:3000"
        }
    }

    stages{
        stage('checkout'){
            git url: "https://github.com/biplabtharu/jenkins/blob/main/simple-node-js-react-npm-app" branch: "main"
        }

        stage('build'){
            steps{
                dir('simple-node-js-react-npm-app'){
                    sh "npm install"
                }
            }
        }

        stage('test'){
            steps{
                dir('simple-node-js-react-npm-app'){
                    sh "./jenkins/scripts/test.sh"
                }
            }
        }
    }
}