pipeline{
    agent{
        docker{
            image "node:slim"
            args "-p 3000:3000"
        }
    }

    stages{
        stage('build'){
            steps{
                sh "npm install"
            }
        }
    }

    stages{
        stage('test'){
            steps{
                sh "./jenkins/scripts/test.sh"
            }
        }
    }
}