pipeline{
    agent{
        docker{
            image "node:slim"
            args "-p 3000:3000"
        }
    }

    stages{
        stage('build'){
            steps{
                dir('simple-node-js-react-npm-app'){
                    sh "npm install"
                }
            }
        }

        stage('test'){
            steps{
                dir('simple-node-js-react-npm-app'){
                    sh "./jenkins/scripts/test.sh"
                }
            }
        }
    }
}