pipeline{
    agent{ docker{ image 'node:20'}}
    environment{
        
    }
    stages{
        stage('Checkout'){
            steps{
                git url: "https://github.com/biplabtharu/jenkins/backend" , branch: "main"
            }
        }

        stage("Install deps"){
            steps{
                sh "npm install"
            }
        }

        stage ("Build"){
            steps{
                sh "npm run build"
            }
        }

        stage("Test"){
            steps{
                echo "Testing stage occurs here"
            }
        }

    }
}