pipeline{
    agent{ docker{ image 'node:20'}}
    environment{
        NPM_CONFIG_CACHE = "tmp/cache"
    }
    stages{
        stage("Install deps"){
            steps{
                dir("LMS_backend"){
                    sh "npm i"
                }
            }
        }

        stage("Create docker image"){
            agent any 
            steps{
                dir("LMS_backend"){
                    echo "Creating docker image"
                    sh "docker build -t LMS_backend:1.0.0 ."
                }
            }
        }
    }
}