pipeline{
    agent{ docker{ image 'node:20'}}
    environment{
        
    }
    stages{
        stage('Checkout'){
            steps{
                git url: "https://github.com/biplabtharu/jenkins/" , branch: "main"
            }
        }

        stage("Install deps"){
            steps{
                dir("LMS_backend"){
                    sh "npm install"
                }
            }
        }

        stage ("Build"){
            steps{
                dir("LMS_backend"){
                    sh "npm run build"
                }
            }
        }

        stage("Test"){
            steps{
                echo "Testing stage occurs here"
            }
        }

    }
}