pipeline{
    agent{ docker{ image 'node:18'}}
    stages{
        stage('Checkout'){
            steps{
                git url: "https://github.com/biplabtharu/jenkins/" , branch: "main"
            }
        }

        stage("Install dependencies"){
            steps{
                dir("LMS_frontend"){
                    sh "npm i"
                }
            }
        }

         stage("Install deps"){
            steps{
                dir("LMS_frontend"){
                    sh "npm run build"
                }
            }
        }

        stage("Test"){
            steps{
                echo "Testing stage occurs here"
            }
        }

    }
}